<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_HomePage</name>
   <tag></tag>
   <elementGuidId>8faafbac-aa61-479d-b3f8-1181bfd203fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@class='dark-logo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>16707500-e67c-49e2-b98a-08801f40ae2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simulate an Interview</value>
      <webElementGuid>9e0ba65e-0ef4-4584-9392-e995447f4a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;section rdContent mb-30 simulateInterview&quot;]/div[@class=&quot;container containerSm&quot;]/div[@class=&quot;inContInner&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-sm-12 col-xs-12&quot;]/h1[1]</value>
      <webElementGuid>c9fd8666-019b-493f-af04-8f01328b4bb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/div/div/h1</value>
      <webElementGuid>69891ac3-16d1-4bd6-a5f2-537da6720c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review peer interview practices.'])[1]/following::h1[1]</value>
      <webElementGuid>f36763bd-f1b3-4e1b-8ccd-ddc9b540aa94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn how to prepare for an interview.'])[1]/following::h1[1]</value>
      <webElementGuid>3347d819-2e50-4a3c-816a-44d585658364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Interview'])[1]/preceding::h1[1]</value>
      <webElementGuid>062b1f07-3c86-490c-9f21-2425df6b238c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simulate an Interview']/parent::*</value>
      <webElementGuid>2f5524d3-1cd0-454a-8404-0e878b9c61f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>abd248e3-009d-4607-8894-b62f38fd78f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Simulate an Interview' or . = 'Simulate an Interview')]</value>
      <webElementGuid>c000d32f-7c9e-4bc4-a77a-b6f40a3e4d64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
