<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_LogIn</name>
   <tag></tag>
   <elementGuidId>d1d487d2-a1a4-4451-915f-e389ddd7aba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.log</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@class='log']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b52e7b0f-95f7-4229-938a-74d32f77ee08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>log</value>
      <webElementGuid>1e2aa91e-12cf-482d-99ea-18dad9678927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>5dee46f4-a31d-4918-9d1f-15fa8d690535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#signin-pop</value>
      <webElementGuid>6dc831b5-d4cc-41f2-8133-022927ac214a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>log in</value>
      <webElementGuid>95c9529a-e742-47d1-8dfa-065c1c6a7efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;no_padding    extPg&quot;]/header[@class=&quot;site-header section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 col-sm-3 col-xs-3 text-right m-hide&quot;]/div[@class=&quot;header-btn clearfix&quot;]/button[@class=&quot;log&quot;]</value>
      <webElementGuid>702244d8-c3c2-4e8f-8665-78cafc4bc638</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/following::button[1]</value>
      <webElementGuid>979c23ed-acff-4af4-a1b0-7256b3a7f2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to main content'])[1]/following::button[2]</value>
      <webElementGuid>effa31c8-a848-4389-9731-abc7ccb75115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sign up'])[1]/preceding::button[1]</value>
      <webElementGuid>6c70ba50-4673-461b-b599-886e88aec106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[2]/preceding::button[1]</value>
      <webElementGuid>b517e4df-eb29-4d10-ab89-c1eeaf797051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='log in']/parent::*</value>
      <webElementGuid>4ebe2536-fe07-4fbd-b3a9-cf2e9e8edcec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>60ca12dc-9340-45f6-b363-33069013640d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'log in' or . = 'log in')]</value>
      <webElementGuid>aca0991b-46be-4fdb-b4e1-422855a0295d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
